# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HackMIT2016' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
  # Pods for HackMIT2016

end
